CREATE TABLE IF NOT EXISTS `cadastro_deposito_logistico` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(255) NOT NULL,
  `nome_fantasia` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(20) NOT NULL,
  `whatsapp` VARCHAR(25) NOT NULL,
  `responsavel` VARCHAR(255) NOT NULL,
  `cargo` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  `bairro` VARCHAR(120) NOT NULL,
  `cidade` VARCHAR(120) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `distancia_centro` DECIMAL(10,2) DEFAULT NULL,
  `tipo_imovel` VARCHAR(100) DEFAULT NULL,
  `tempo_ocupacao` VARCHAR(100) DEFAULT NULL,
  `area_terreno` DECIMAL(12,2) DEFAULT NULL,
  `area_coberta` DECIMAL(12,2) DEFAULT NULL,
  `area_patio` DECIMAL(12,2) DEFAULT NULL,
  `tipo_estrutura` VARCHAR(100) DEFAULT NULL,
  `tipo_piso` VARCHAR(100) DEFAULT NULL,
  `pe_direito` VARCHAR(100) DEFAULT NULL,
  `veiculos_json` LONGTEXT DEFAULT NULL,
  `restricao_acesso` VARCHAR(120) DEFAULT NULL,
  `obs_acesso` TEXT DEFAULT NULL,
  `cap_paletes` INT DEFAULT NULL,
  `cap_toneladas` DECIMAL(12,2) DEFAULT NULL,
  `qtd_docas` INT DEFAULT NULL,
  `possui_docas` VARCHAR(10) DEFAULT NULL,
  `equip_json` LONGTEXT DEFAULT NULL,
  `qtd_equip` VARCHAR(255) DEFAULT NULL,
  `colaboradores` INT DEFAULT NULL,
  `funcionamento` VARCHAR(100) DEFAULT NULL,
  `seg_json` LONGTEXT DEFAULT NULL,
  `serv_json` LONGTEXT DEFAULT NULL,
  `cargas_json` LONGTEXT DEFAULT NULL,
  `restricoes_carga` TEXT DEFAULT NULL,
  `observacoes` TEXT DEFAULT NULL,
  `fotos_json` LONGTEXT DEFAULT NULL,
  `ip_origem` VARCHAR(45) DEFAULT NULL,
  `user_agent` VARCHAR(1000) DEFAULT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_criado_em` (`criado_em`),
  KEY `idx_cnpj` (`cnpj`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `cadastro_licenciamento_marca` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_interessado` VARCHAR(255) NOT NULL,
  `empresa` VARCHAR(255) DEFAULT NULL,
  `cnpj` VARCHAR(20) DEFAULT NULL,
  `cargo` VARCHAR(120) DEFAULT NULL,
  `whatsapp` VARCHAR(25) NOT NULL,
  `email` VARCHAR(255) DEFAULT NULL,
  `cidade` VARCHAR(120) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  `qtd_caminhoes` VARCHAR(60) NOT NULL,
  `tipos_operacao_json` LONGTEXT DEFAULT NULL,
  `fretes_mensais` INT DEFAULT NULL,
  `ticket_medio` DECIMAL(12,2) DEFAULT NULL,
  `faturamento_estimado` DECIMAL(14,2) DEFAULT NULL,
  `regiao_interesse` VARCHAR(120) DEFAULT NULL,
  `territorio_interesse` VARCHAR(255) DEFAULT NULL,
  `modalidades_interesse_json` LONGTEXT DEFAULT NULL,
  `possui_base_operacional` VARCHAR(30) DEFAULT NULL,
  `area_base` DECIMAL(12,2) DEFAULT NULL,
  `equipe_operacional` INT DEFAULT NULL,
  `investimento_disponivel` VARCHAR(120) DEFAULT NULL,
  `prazo_implantacao` VARCHAR(120) DEFAULT NULL,
  `observacoes` TEXT DEFAULT NULL,
  `anexos_json` LONGTEXT DEFAULT NULL,
  `ip_origem` VARCHAR(45) DEFAULT NULL,
  `user_agent` VARCHAR(1000) DEFAULT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_licenciamento_criado_em` (`criado_em`),
  KEY `idx_licenciamento_cidade_estado` (`cidade`, `estado`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `cadastro_motorista_contrato` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `rntrc` VARCHAR(40) NOT NULL,
  `whatsapp` VARCHAR(25) NOT NULL,
  `email` VARCHAR(255) DEFAULT NULL,
  `placa_cavalo` VARCHAR(8) DEFAULT NULL,
  `placa_carreta_1` VARCHAR(8) DEFAULT NULL,
  `placa_carreta_2` VARCHAR(8) DEFAULT NULL,
  `categoria_veiculo` VARCHAR(60) NOT NULL,
  `modalidades_json` LONGTEXT DEFAULT NULL,
  `formas_contratacao_json` LONGTEXT DEFAULT NULL,
  `valor_frete` DECIMAL(12,2) DEFAULT NULL,
  `prazo_pagamento` VARCHAR(120) DEFAULT NULL,
  `formas_pagamento_json` LONGTEXT DEFAULT NULL,
  `prazo_contrato_dias` INT DEFAULT NULL,
  `foro_juridico` VARCHAR(120) DEFAULT NULL,
  `aceite_clausulas` VARCHAR(3) DEFAULT NULL,
  `aceite_lgpd` VARCHAR(3) DEFAULT NULL,
  `observacoes` TEXT DEFAULT NULL,
  `anexos_json` LONGTEXT DEFAULT NULL,
  `ip_origem` VARCHAR(45) DEFAULT NULL,
  `user_agent` VARCHAR(1000) DEFAULT NULL,
  `criado_em` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_motorista_criado_em` (`criado_em`),
  KEY `idx_motorista_cpf` (`cpf`),
  KEY `idx_motorista_rntrc` (`rntrc`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
